function X = flip( X, mirror )
%FLIP flip left-right of the data instance

if nargin < 2
    % list of synmetric body parts
    mirror = [...
         3, 15;...
         4, 16;...
         5, 17;...
         6, 18;...
         7, 19;...
         8, 20;...
         9, 21;...
        10, 22;...
        11, 23;...
        12, 24;...
        13, 25;...
        14, 26;...
        ];
end
mirror = [mirror(:),[mirror(:,2);mirror(:,1)]];

for i = 1:numel(X)
    if ischar(X(i).im), X(i).im = imread(X(i).im); end
    X(i).im = flipdim(X(i).im,2);
    w = size(X(i).im,2);
    X(i).point(:,1) = w - X(i).point(:,1) + 1;
    X(i).point(mirror(:,1),:) = X(i).point(mirror(:,2),:);
    X(i).labels = flipdim(X(i).labels,2);
end

end

