% add an exemplar to the database
function add_exemplar( ...
   features, ...
   x_pos, ...
   y_pos, ...
   class_id)

% add exemplar 
mex_category_db( ...
   'add_exemplar', ...  
   features', ...
   x_pos, ...
   y_pos, ...
   class_id - 1);
