% query database for an exemplar
function id_vec = query_db( ...
   features, ...
   x_pos, ...
   y_pos, ...
   num_nn, ...
   item_limit)

id_vec = mex_category_db( ...
   'query_db', ...
   features', ...
   x_pos, ...
   y_pos, ...
   num_nn, ...
   item_limit);

id_vec = id_vec + 1;
